# Site settings
title: QQorp
email: contact@qqorp.com
description: > # TODO
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qqorp.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  QQorp

# Build settings
markdown: kramdown
